<a href="https://colab.research.google.com/github/MarAndreaFernandez/TC2004B/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


0-D Arrays, o escalares

In [ ]:
a0 = np.array(42)
print(a0)

42


1-D Array


In [ ]:
a1 = np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [ ]:
2-D Array

In [ ]:
a2 = np.array([(1,2,3,4),(4,3,2,1)])
print(a2)

[[1 2 3 4]
 [4 3 2 1]]


3-D Array

In [ ]:
a3 = np.array([[(1,2,3,4),(4,3,2,1)],[(1,2,3,4),(4,3,2,1)]])
print(a3)

[[[1 2 3 4]
  [4 3 2 1]]

 [[1 2 3 4]
  [4 3 2 1]]]


In [ ]:
ndim nos da las dimensiones de un array

In [ ]:
print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


0
1
2
3


Podemos definir las dimensiones de nuestro array

In [ ]:
arr = np.array([1,2,3,4], ndmin = 5)

print(arr)

print('El numero de dimensiones es: ', arr.ndim)

[[[[[1 2 3 4]]]]]
El numero de dimensiones es:  5


**Indexing**

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Segundo elemento de la primer renglon: ', arr[0,1])
print('Segundo renglon, quinta columna: ', arr[1,4])

Segundo elemento de la primer renglon:  2
Segundo renglon, quinta columna:  10


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('Tercer elemento de el segundo array del primer array: ', arr[0,1,2])

Tercer elemento de el segundo array del primer array:  6


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Ultimo elemnto de la segunda dimension', arr[1,-1])

Ultimo elemnto de la segunda dimension 10


**Slicing**

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-4:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[4 5 6]
[2 4]
[1 3 5 7]


Slicing dos dimensiones